// 谁是卧底 - 国家词库：每对词是相似但不同的国家
export interface WordPair {
  civilian: string; // 平民词
  spy: string;      // 卧底词
}

export const countryPairs: WordPair[] = [
  { civilian: "中国", spy: "日本" },
  { civilian: "美国", spy: "加拿大" },
  { civilian: "法国", spy: "意大利" },
  { civilian: "德国", spy: "奥地利" },
  { civilian: "英国", spy: "爱尔兰" },
  { civilian: "韩国", spy: "朝鲜" },
  { civilian: "泰国", spy: "越南" },
  { civilian: "澳大利亚", spy: "新西兰" },
  { civilian: "巴西", spy: "阿根廷" },
  { civilian: "西班牙", spy: "葡萄牙" },
  { civilian: "瑞典", spy: "挪威" },
  { civilian: "印度", spy: "巴基斯坦" },
  { civilian: "埃及", spy: "摩洛哥" },
  { civilian: "墨西哥", spy: "哥伦比亚" },
  { civilian: "俄罗斯", spy: "乌克兰" },
  { civilian: "荷兰", spy: "比利时" },
  { civilian: "瑞士", spy: "卢森堡" },
  { civilian: "希腊", spy: "土耳其" },
  { civilian: "新加坡", spy: "马来西亚" },
  { civilian: "南非", spy: "尼日利亚" },
  { civilian: "芬兰", spy: "丹麦" },
  { civilian: "伊朗", spy: "伊拉克" },
  { civilian: "智利", spy: "秘鲁" },
  { civilian: "波兰", spy: "捷克" },
  { civilian: "古巴", spy: "牙买加" },
  { civilian: "以色列", spy: "黎巴嫩" },
  { civilian: "匈牙利", spy: "罗马尼亚" },
  { civilian: "菲律宾", spy: "印度尼西亚" },
  { civilian: "冰岛", spy: "格陵兰" },
  { civilian: "蒙古", spy: "哈萨克斯坦" },
  { civilian: "柬埔寨", spy: "老挝" },
  { civilian: "缅甸", spy: "孟加拉国" },
  { civilian: "斯里兰卡", spy: "马尔代夫" },
  { civilian: "尼泊尔", spy: "不丹" },
  { civilian: "阿联酋", spy: "卡塔尔" },
  { civilian: "沙特阿拉伯", spy: "阿曼" },
  { civilian: "约旦", spy: "叙利亚" },
  { civilian: "肯尼亚", spy: "坦桑尼亚" },
  { civilian: "加纳", spy: "科特迪瓦" },
  { civilian: "埃塞俄比亚", spy: "索马里" },
  { civilian: "刚果", spy: "喀麦隆" },
  { civilian: "委内瑞拉", spy: "厄瓜多尔" },
  { civilian: "乌拉圭", spy: "巴拉圭" },
  { civilian: "玻利维亚", spy: "巴拿马" },
  { civilian: "哥斯达黎加", spy: "危地马拉" },
  { civilian: "多米尼加", spy: "海地" },
  { civilian: "克罗地亚", spy: "塞尔维亚" },
  { civilian: "斯洛伐克", spy: "斯洛文尼亚" },
  { civilian: "立陶宛", spy: "拉脱维亚" },
  { civilian: "爱沙尼亚", spy: "白俄罗斯" },
  { civilian: "格鲁吉亚", spy: "亚美尼亚" },
  { civilian: "阿塞拜疆", spy: "土库曼斯坦" },
  { civilian: "乌兹别克斯坦", spy: "吉尔吉斯斯坦" },
  { civilian: "摩纳哥", spy: "列支敦士登" },
  { civilian: "马耳他", spy: "塞浦路斯" },
  { civilian: "文莱", spy: "东帝汶" },
  { civilian: "巴布亚新几内亚", spy: "斐济" },
  { civilian: "牙买加", spy: "特立尼达" },
  { civilian: "阿尔及利亚", spy: "突尼斯" },
  { civilian: "利比亚", spy: "苏丹" },
];

export function getRandomPair(): WordPair {
  return countryPairs[Math.floor(Math.random() * countryPairs.length)];
}
